### ISSUE TITLE
No Windows Support - should mention in README.md

### ISSUE THREAD

**Issue by aggieben** [black-screen/black-screen#24]
:cry: The installer doesn't work on Windows:

```
C:\Users\Benjamin\src\black-screen [master]
λ npm run install-all

> black-screen@0.0.1 install-all C:\Users\Benjamin\src\black-screen
> PATH=node_modules/.bin:$PATH rm -rf node_modules && npm install && bower install && npm run rebuild-pty

'npm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Benjamin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "install-all"
npm ERR! node v0.12.4
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 install-all: `PATH=node_modules/.bin:$PATH rm -rf node_modules && npm install && bower install && npm run rebuild-pty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 install-all script 'PATH=node_modules/.bin:$PATH rm -rf node_modules && npm install && bower install && npm run rebuild-pty'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     PATH=node_modules/.bin:$PATH rm -rf node_modules && npm install && bower install && npm run rebuild-pty
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Benjamin\src\black-screen\npm-debug.log
```

I presume this to mean that Windows support isn't even a thing.  That's all fine and good; project owners do what they want.  However, it would have been helpful to me to have a blurb in the README that would have prevented me from getting my hopes up :-)

**Comment by talklittle** [comment]
I got a little further, but no dice for me either:

1. Install [node.js](https://nodejs.org/en/)
2. Navigate to https://registry.npmjs.org/ in your browser to [fix ECONNRESET](http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset)
3. Install [Python 2.7](https://www.python.org/downloads/)
4. Install [.NET Framework](https://msdn.microsoft.com/en-us/vstudio/aa496123.aspx) to get VCBuild.exe
5. `npm config set msvs_version 2015 --global` [to set msvs_version](http://stackoverflow.com/a/22411007/57490)
6. `npm install`

```
C:\Users\andrew\Documents\black-screen\node_modules\child_pty>if not defined npm
_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bi
n\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\andrew\Documents\black-screen\node_modules\child_pty\build\exechelper.
vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.pr
ops" was not found. Confirm that the path in the <Import> declaration is correc
t, and that the file exists on disk.
C:\Users\andrew\Documents\black-screen\node_modules\child_pty\build\pty.vcxproj
(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" wa
s not found. Confirm that the path in the <Import> declaration is correct, and
that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\andrew\Documents\black-screen\node_modules\child_pty
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! child_pty@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the child_pty@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the child_pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls child_pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\andrew\Documents\black-screen\npm-debug.log
```

**Comment by kowsheek** [comment]
:+1:

**Comment by shockone** [comment]
I would like Black Screen to work on Windows. If somebody uses Windows and is willing to collaborate, I would gratefully accept a pull request that fixes the installation.

**Comment by mackenza** [comment]
even if you don't make it work on Windows, at least call it out in the README, please. (oh and Linux too)

**Comment by shockone** [comment]
Added.

**Comment by iiegor** [comment]
@shockone I got it working on windows but there are many things to consider.

## Issues
- **child_pty** actually have many problems when trying to build for windows
- Each command invocate a new shell process
- black-screen uses platform dependent code (e.g: process.env.HOME in windows is process.env.USERPROFILE)
- Need to fix npm scripts, on windows need to run them manually

**Comment by iiegor** [comment]
## Some improvements:
- Basic commands working.
- Use of buffered process.
- Platform code dependant removed.
- CSS Improvements
- Clear command working as built-in by typing clear or with hotkeys (the last already exists)

## Result
![alt](http://i.imgur.com/raDSn56.png)

**Comment by kowsheek** [comment]
You're a magician @iiegor!

I tried for a few hours to get `child_pty` to install and gave up. Please share your install steps so we can send in some PRs.

**Comment by iiegor** [comment]
It's very easy!

Follow these steps and ignore all realted child_pty messages:
- ``npm install``
- ``bower install``

When you have the dependencies run ``gulp`` for build and when it finishes (watch task) drag the **black-screen** folder to the electron-prebuilt executable located in **node_modules\electron-prebuilt\dist**.

Now you can see black-screen but won't work you need to remove the platform-dependent code and find a way to replace the child_pty module that is missing.

**Comment by shockone** [comment]
Hey, guys. Please try to install it with the latest master. Note that the install command has changed from `npm run install-all` to `npm install`.

**Comment by kowsheek** [comment]
I got errors while installing:

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(361): warning C4577: 'noexcept' used
with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compilin g source file ..\..\..\deps\winpty\agent\ConsoleInput.cc) [E:\projects\black-screen\node_modules\pty.js\build\ deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\EventLoop.cc(69): error C2039: 'max': is not a member of 'std' [E:\projects\black-s creen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\EventLoop.cc(69): error C3861: 'max': identifier not found [E:\projects\black-scree n\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\EventLoop.cc(68): warning C4390: ';': empty controlled statement found; is this the  intent? [E:\projects\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  main.cc
  DebugClient.cc
..\..\..\deps\winpty\agent\NamedPipe.cc(153): error C2039: 'min': is not a member of 'std' [E:\projects\black- screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(153): error C3861: 'min': identifier not found [E:\projects\black-scre en\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C2039: 'min': is not a member of 'std' [E:\projects\black- screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C3861: 'min': identifier not found [E:\projects\black-scre en\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C2039: 'min': is not a member of 'std' [E:\projects\black- screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C3861: 'min': identifier not found [E:\projects\black-scre en\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(361): warning C4577: 'noexcept' used
with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compilin g source file ..\..\..\deps\winpty\agent\Coord.cc) [E:\projects\black-screen\node_modules\pty.js\build\deps\wi npty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(60): error C3688: invalid literal suffix 'CSI'; literal operator or lit eral operator template 'operator ""CSI' not found [E:\projects\black-screen\node_modules\pty.js\build\deps\win pty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(59): warning C4390: ';': empty controlled statement found; is this the
intent? [E:\projects\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(165): error C3688: invalid literal suffix 'CSI'; literal operator or li teral operator template 'operator ""CSI' not found [E:\projects\black-screen\node_modules\pty.js\build\deps\wi npty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(165): error C2664: 'int sprintf(char *const ,const char *const ,...)':
cannot convert argument 2 from 'int' to 'const char *const ' [E:\projects\black-screen\node_modules\pty.js\bui ld\deps\winpty\winpty-agent.vcxproj]
  ..\..\..\deps\winpty\agent\Terminal.cc(165): note: Conversion from integral type to pointer type requires re
  interpret_cast, C-style cast or function-style cast
..\..\..\deps\winpty\agent\Terminal.cc(190): error C3688: invalid literal suffix 'CSI'; literal operator or li teral operator template 'operator ""CSI' not found [E:\projects\black-screen\node_modules\pty.js\build\deps\wi npty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(190): error C2664: 'int sprintf(char *const ,const char *const ,...)':
cannot convert argument 2 from 'int' to 'const char *const ' [E:\projects\black-screen\node_modules\pty.js\bui ld\deps\winpty\winpty-agent.vcxproj]
  ..\..\..\deps\winpty\agent\Terminal.cc(190): note: Conversion from integral type to pointer type requires re
  interpret_cast, C-style cast or function-style cast
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(361): warning C4577: 'noexcept' used
with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compilin g source file ..\..\..\deps\winpty\agent\Win32Console.cc) [E:\projects\black-screen\node_modules\pty.js\build\ deps\winpty\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(361): warning C4577: 'noexcept' used
with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compilin g source file ..\..\..\deps\winpty\agent\SmallRect.cc) [E:\projects\black-screen\node_modules\pty.js\build\dep s\winpty\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used wit h no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling s ource file ..\..\..\deps\winpty\agent\Agent.cc) [E:\projects\black-screen\node_modules\pty.js\build\deps\winpt y\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used wit h no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling s ource file ..\..\..\deps\winpty\agent\main.cc) [E:\projects\black-screen\node_modules\pty.js\build\deps\winpty \winpty-agent.vcxproj]
  winpty.cc
  DebugClient.cc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception hand ler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\..\..\deps\winpty\libw inpty\winpty.cc) [E:\projects\black-screen\node_modules\pty.js\build\deps\winpty\winpty.vcxproj]
..\..\..\deps\winpty\libwinpty\winpty.cc(139): error C3688: invalid literal suffix 'AGENT_EXE'; literal operat or or literal operator template 'operator ""AGENT_EXE' not found [E:\projects\black-screen\node_modules\pty.js \build\deps\winpty\winpty.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Vendors\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Vendors\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\projects\black-screen\node_modules\pty.js
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN prefer global babel@5.8.23 should be installed with -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Vendors\\nodejs\\\\node.exe" "C:\\Vendors\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Vendors\\nodejs\\\\node.exe" "C:\\Vendors\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm WARN prefer global node-gyp@3.0.1 should be installed with -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Vendors\\nodejs\\\\node.exe" "C:\\Vendors\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\projects\black-screen\npm-debug.log`

Not sure if it's because of build tools.

**Comment by shockone** [comment]
This comment suggests a fix. https://github.com/black-screen/black-screen/pull/56#issuecomment-138678235

**Comment by YaManicKill** [comment]
I'm still having some issues with installing on windows. Seems like pty.js doesn't want to be installed.

```
C:\dev\black-screen>npm i

> pty.js@0.3.0 install C:\dev\black-screen\node_modules\pty.js
> node-gyp rebuild


C:\dev\black-screen\node_modules\pty.js>if not defined npm_config_node_gyp (node
 "C:\dev\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\
node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [C:\dev\black-screen\node_modules\pty.js\build\deps\winpty
\winpty-agent.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [C:\dev\black-screen\node_modules\pty.js\build\deps\winpty
\winpty.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\npm\node_modules\npm\node_modu
les\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\npm\\node_modul
es\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\black-screen\node_modules\pty.js
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.7
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\npm\\node_modules\
\npm\\bin\\npm-cli.js" "i"
npm ERR! node v5.1.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\black-screen\npm-debug.log
```

**Comment by shockone** [comment]
We switched back to using `pty.js`, which means it won't work on Windows.
