### ISSUE TITLE
Replace the child_pty Library with pty.js

### ISSUE THREAD

**Issue by flawiddsouza** [black-screen/black-screen#83]
As quite a few people have noted, including me. There seems to be an issue with the ```child_pty``` module, which prevents Black Screen from building on all three of these platforms on several different occasions:
- Windows: https://github.com/black-screen/black-screen/issues/24
- Linux: https://github.com/shockone/black-screen/issues/49
- Mac OSX: https://github.com/black-screen/black-screen/issues/27

There seem to workarounds but it would be better if the problem didn't arise in the first place.

Any ideas what could be causing this? Some have said its the NaN version that the module seems to require. 

Solving this problem would be a major step in development for Black Screen. This could essentially enable full multi-platform support for it.

**Comment by shockone** [comment]
`child_pty` is the only native module, that's why it causes problems. Also the fact, that building it with Electron's headers isn't the usual workflow. 

This is too level for me, but as far as I understand, it creates a pair of device files in order to pretend being a PTY. Since both the author of `child_pty` and the author of [pty.js](https://github.com/chjj/pty.js/) use a native extension for that, I guess it's not possible to do it using only node.js platform, but I might be wrong here.

So, the only option I see is to switch to pty.js. It has better support, and now it includes all the features we need. However, after rebuilding it with the Electron's headers, for some reason it becomes insanely slow. It wasn't like that a month ago. 

I'll create an issue for that.

**Comment by shockone** [comment]
If you don't mind, I'll rename this one instead.

The replacement is really easy: in `package.json` we need to substitute `child_pty` with `pty.js` (two places) and change its version. And then there are two `require`s, which should be renamed. After that 
`npm run install-all` to install and rebuild the new dependency. No other code changes are required. 

But now executing any command has a 2 second delay, which we need to debug.

**Comment by flawiddsouza** [comment]
@shockone Maybe a temporary dev branch for testing is in order.

**Comment by shockone** [comment]
@flawiddsouza, surely, we create a branch for each feature.

**Comment by flawiddsouza** [comment]
@shockone Hopefully we won't have too many issues after this.

**Comment by shockone** [comment]
I'll start working on it. It seems to be the most painful issue.

**Comment by flawiddsouza** [comment]
@shockone Can you signup for https://gitter.im/ so we can talk about Black Screen without creating unecessary issues? [I'll delete this comment as soon as you acknowledge it]

**Comment by shockone** [comment]
@flawiddsouza, I'm there.

**Comment by flawiddsouza** [comment]
@shockone I can't seem to find you or Black screen.

**Comment by shockone** [comment]
A fix: https://github.com/black-screen/black-screen/pull/88
